#!/usr/bin/env bash
# install nginx

sudo apt-get update -y
sudo apt-get install nginx -y
sudo chown -R $USER:$USER /var/www/html
sudo echo "Holberton School" > /var/www/html/index.html
sudo service nginx restart
